---

- name: configure SNMP Access List
  ios_config:
    lines: access-list 42 permit 10.255.0.70 0.0.0.0

- name: Setup community string
  ios_config:
    lines: snmp-server community jrbygRO ro 42

- name: Enable trap config
  ios_config:
    lines: snmp-server enable traps config

- name: Enable trap ospf for routers
  ios_config:
    lines: snmp-server enable traps ospf
  when: inventory_hostname in groups['Routers']

- name: Enable trap ospf for Distribution switches
  ios_config:
    lines: snmp-server enable traps ospf
  when: inventory_hostname in groups['DisSw']

- name: Enable trap hsrp
  ios_config:
    lines: snmp-server enable traps hsrp
  when: inventory_hostname in groups['DisSW']

- name: Enable trap port security
  ios_config:
    lines: snmp-server enable traps port-security
  when: inventory_hostname in groups['AccSW']

- name: Set trap source for routers
  ios_config:
    lines: snmp-server trap-source Loopback1
  when: inventory_hostname in groups['Routers']

- name: Set trap source for switches
  ios_config:
    lines: snmp-server trap-source Vlan 5
  when: inventory_hostname in groups['Switches']

- name: configure SNMP collector address
  ios_config:
    lines: snmp-server host 10.255.0.70 traps jrbygRO