---

- name: configure SNMP Access List
  ios_config:
    lines: access-list 42 permit 10.255.0.70

- name: Setup community string
  ios_config:
    lines: snmp-server community jrbygRO RO 42

- name: Enable trap 
  ios_config:
    lines: snmp-server enable traps

- name: Set trap source for routers
  ios_config:
    lines: snmp-server trap-source Loopback1
  when: inventory_hostname in groups['Routers']

- name: Set trap source for switches
  ios_config:
    lines: snmp-server trap-source Vlan 5
  when: inventory_hostname in groups['Switches']

- name: configure SNMP collector address
  ios_config:
    lines: snmp-server host 10.255.0.70 traps jrbygRO