---

- name: Setup af Cisco devices
  hosts: Network
  gather_facts: false
  connection: network_cli
  roles:
#    - system
#    - NTP
    - VLANS
    - SaveConfig
  tags:
    - Cisco
    - NetworkDevices

- name: Setup DHCP
  hosts: DHCP01
  gather_facts: false
#  roles:
#    - DHCP
  tags:
    - DHCP

- name: Setup Radius clients
  hosts: Radius01
  gather_facts: false
#  roles:
#    - SetupRadius
  tags:
    - Radius