---

- name: Setup of generel parametres on Cisco devices
  hosts: Network
  gather_facts: false
  connection: network_cli
  roles:
    - system

- name: Setup time configuration on Cisco devices
  hosts: Network
  gather_facts: false
  connection: network_cli
  roles:
    - NTP
  tags:
    - NTP

- name: Setup of Cisco Switches
  hosts: Switches
  gather_facts: false
  connection: network_cli
  roles:
    - VLANS
  tags:
    VLANS

- name: Save final config on Cisco devices
  hosts: Network
  gather_facts: false
  connection: network_cli
  roles:
    - SaveConfig

- name: Setup DHCP
  hosts: DHCP01
  gather_facts: false
  roles:
    - DHCP
  tags:
    - DHCP

- name: setup default settings on Linux Servers
  hosts: LinuxServers
  gather_facts: false
  become: yes
  become_method: sudo
  roles:
    - LinuxServerSetup
  tags:
    - Linux