---

#- name: Create vlans on access switches
#  ios_config: 
#    src: templates/AcVlan.j2
#    match: none

- name: Assign interfaces fa0/1 - 4 to VLAN 255
  ios_config:
    lines: 
    - no shutdown
    - switchport mode access
    - switchport access vlan 255
    parents: interface range FastEthernet0/1 - 4
  when: inventory_hostname in groups['AccSW']

- name: Assign interfaces fa0/5 - 8 to VLAN 10
  ios_config:
    lines: 
    - no shutdown
    - switchport mode access
    - switchport access vlan 10
    parents: interface range FastEthernet0/5 - 8
  when: inventory_hostname in groups['AccSW']  

- name: Assign interfaces fa0/9 - 12 to VLAN 20
  ios_config:
    lines: 
    - switchport mode access
    - switchport access vlan 30
    parents: "{{ item }}"
  loop:
    - interface FastEthernet0/9
    - interface FastEthernet0/10
    - interface FastEthernet0/11
    - interface FastEthernet0/12
  when: inventory_hostname in groups['AccSW']

#- name: Create vlans on Distrubations switches
#  ios_config:
#    src: templates/DisVlan.j2
#    match: none

#- name: Setup STP and set root and backup root bridge on VLANs
#  ios_config:
#    src: templates/STP.j2
#    match: none