---

#- name: Create vlans on access switches
#  ios_config: 
#    src: templates/AcVlan.j2
#    match: none

- name: Assign interfaces fa0/1 - 4 to VLAN 255
  ios_config:
    lines: 
    - no shutdown
    - switchport mode access
    - switchport access vlan 255
    parents: interface FastEthernet0/"{{ item }}"
  loop:
    - 1
    - 2
    - 3
    - 4  
  when: inventory_hostname in groups['AccSW']

- name: Assign interfaces fa0/5 - 8 to VLAN 10
  ios_config:
    lines: 
    - no shutdown
    - switchport mode access
    - switchport access vlan 30
    parents: interface FastEthernet0/"{{ item }}"
  loop:
    - 5
    - 6
    - 7
    - 8 
  when: inventory_hostname in groups['AccSW']  

- name: Assign interfaces fa0/9 - 12 to VLAN 20
  ios_config:
    lines: 
    - no shutdown
    - switchport mode access
    parents: interface FastEthernet0/"{{ item }}"
  loop:
    - 9
    - 10
    - 11
    - 12 
  when: inventory_hostname in groups['AccSW']

#- name: Create vlans on Distrubations switches
#  ios_config:
#    src: templates/DisVlan.j2
#    match: none

#- name: Setup STP and set root and backup root bridge on VLANs
#  ios_config:
#    src: templates/STP.j2
#    match: none