---

- name: Create vlans on access switches
  ios_config: 
    src: templates/AcVlan.j2
    match: none
  changed_when: False

- name: config trunk on Distribution switches
  ios_config:
    lines:
    - switchport trunk encapsulation dot1q
    - switchport trunk allowed vlan 5,10,20,30,40,50,60,70,255
    - switchport mode trunk
    parents: "{{ item }}"
  with_items: 
    - interface FastEthernet0/3
    - interface FastEthernet0/24
  when: inventory_hostname in groups['DisSW']

- name: Assign interfaces fa0/1 - 4 to VLAN 255
  ios_config:
    lines:
    - switchport mode access
    - switchport access vlan 255
    parents: "{{ item }}"
  with_items:
    - interface FastEthernet0/1
    - interface FastEthernet0/2
    - interface FastEthernet0/3
    - interface FastEthernet0/4
  when: inventory_hostname in groups['VibAccSW']

- name: Assign interfaces fa0/5 - 8 to VLAN 10
  ios_config:
    lines: 
    - switchport mode access
    - switchport access vlan 10
    parents: "{{ item }}"
  with_items:
    - interface FastEthernet0/5
    - interface FastEthernet0/6
    - interface FastEthernet0/7
    - interface FastEthernet0/8
  when: inventory_hostname in groups['AccSW']  

- name: Assign interfaces fa0/9 - 12 to VLAN 20
  ios_config:
    lines: 
    - switchport mode access
    - switchport access vlan 20
    parents: "{{ item }}"
  with_items:
    - interface FastEthernet0/9
    - interface FastEthernet0/10
    - interface FastEthernet0/11
    - interface FastEthernet0/12
  when: inventory_hostname in groups['AccSW']

- name: Create vlans on Distrubations switches
  ios_config:
    src: templates/DisVlan.j2
    match: none
  changed_when: False

- name: Setup STP and set root and backup root bridge on VLANs
  ios_config:
    src: templates/STP.j2
    match: none
  changed_when: False