ansible_user: "{{ vault_win_user }}"
ansible_password: "{{ vault_win_pass }}"
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: ignore