---
## Tasks for the network device system
- name: Clear unneeded banners
  hosts: Network
  ios_banner:
    banner: "{{ item }}"
    state: absent
  loop:
  - motd
  - exec
  - incoming

- name: Update login banner
  hosts: Network
  ios_banner:
    banner: login
    text: |
      ---------------------------------------------------------
      |
      | Denne enhed tilhoerer JR-Byg - No unauthorized access!
      |
      ---------------------------------------------------------
      |
      | Du er logged ind paa {{ inventory_hostname }}, Biatch!
      |
      ---------------------------------------------------------
    state: present

- name: Disable DNS 
  hosts: Network
  cisco.ios.ios.system:
    lookup_enabled: no