---
## Tasks for the network device system
- name: SSH only
  ios_config:
    lines:
      - ip ssh version 2
      - line vty 0 15
      - transport input ssh

- name: Clear unneeded banners
  ios_banner:
    banner: "{{ item }}"
    state: absent
  loop:
  - motd
  - exec
  - incoming

- name: Update login banner
  ios_banner:
    banner: login
    text: |
      ---------------------------------------------------------
      |
      | Denne enhed tilhoerer JR-Byg - No unauthorized access!
      |
      ---------------------------------------------------------
      |
      | Du er logged ind paa {{ inventory_hostname }}, Biatch!
      |
      ---------------------------------------------------------
    state: present

- name: Disable DNS
  ios_system:
    lookup_enabled: no

- name: Password-Encryption
  ios_config:
    lines:
      - service password-encryption

- name: configure log buffer
  ios_logging:
    dest: buffered
    level: informational
    state: present

- name: Syslog
  ios_logging:
    dest: host
    name: "{{ log_host }}"
    state: present

