---
## Tasks for the network device system
- name: Set hostname
  ios_system:
    hostname: "{{ inventory_hostname }}"

- name: SSH Version 2
  ios_config:
    lines: ip ssh version 2

- name: Set VTY lines to only SSH
  ios_config:
    lines: transport input ssh
    parents: "{{ item }}"
  loop:
    - line vty 0 4
    - line vty 5 15

- name: Clear unneeded banners
  ios_banner:
    banner: "{{ item }}"
    state: absent
  loop:
  - motd
  - exec
  - incoming

- name: Update login banner
  ios_banner:
    banner: login
    text: |
      ---------------------------------------------------------
      |
      | Denne enhed tilhoerer JR-Byg - No unauthorized access!
      |
      ---------------------------------------------------------
      |
      | Du er logged ind paa {{ inventory_hostname }}, Biatch!
      |
      ---------------------------------------------------------
    state: present

- name: Disable DNS
  ios_system:
    lookup_enabled: no

- name: Password-Encryption
  ios_config:
    lines: service password-encryption

- name: configure log buffer
  ios_logging:
    dest: buffered
    level: informational
    state: present

- name: Syslog
  ios_logging:
    dest: host
    name: "{{ log_host }}"
    state: present

- name: enable aaa on switches
  ios_config:
    lines: aaa new-model
  
- name: setup radius server group
  ios_config:
    lines: server-private {{ radius_host }} auth-port 1645 acct-port 1646 key {{ vault_radius_shared_secret }}
    parents: aaa group server radius JRradius

- name: set source interface
  ios_config:
    lines: ip radius source-interface {{ dev_mang_int }}

- name: Config Radius AAA
  ios_config:
    lines:
    - aaa authentication login JR_rad group JRradius local
    - aaa authorization exec JR_rad group JRradius local if-authenticated
    - aaa accounting exec default start-stop group JRradius

- name: apply on vty lines
  ios_config:
    lines:
    - authorization exec JR_rad
    - login authentication JR_rad
    parents: "{{ item }}"
  loop:
    - line vty 0 4
    - line vty 5 15