---
## Tasks for the network device system
- name: SSH Version 2
  ios_config:
    lines: ip ssh version 2

- name: Set VTY lines to only SSH
  ios_config:
    lines: transport input ssh
    parents: "{{ item }}"
  loop:
    - line vty 0 4
    - line vty 5 15

- name: Clear unneeded banners
  ios_banner:
    banner: "{{ item }}"
    state: absent
  loop:
  - motd
  - exec
  - incoming

- name: Update login banner
  ios_banner:
    banner: login
    text: |
      ---------------------------------------------------------
      |
      | Denne enhed tilhoerer JR-Byg - No unauthorized access!
      |
      ---------------------------------------------------------
      |
      | Du er logged ind paa {{ inventory_hostname }}, Biatch!
      |
      ---------------------------------------------------------
    state: present

- name: Disable DNS
  ios_system:
    lookup_enabled: no

- name: Password-Encryption
  ios_config:
    lines: service password-encryption

- name: configure log buffer
  ios_logging:
    dest: buffered
    level: informational
    state: present

- name: Syslog
  ios_logging:
    dest: host
    name: "{{ log_host }}"
    state: present

#- name: Config Radius AAA
#  ios_config:
#    lines:
#    - aaa new-model
#    - aaa group server radius JRradius
#    - server-private "{{ radius_host }}" auth-port 1645 acct-port 1646 key "{{ vault_radius_shared_secret }}"
#    - ip radius source-interface "{{ dev_mang_int }}"
#    match: none